import {
  Complaint,
  WaterNotice,
  FacilityDashboardStats,
  Staff,
  ComplaintDistribution,
} from '../types/facilityTypes';

export const MOCK_DASHBOARD_STATS: FacilityDashboardStats = {
  pendingComplaints: 5,
  resolvedIssues: 23,
  waterUsage: 38500,
  scheduledMaintenance: 3,
};

export const MOCK_COMPLAINT_DISTRIBUTION: ComplaintDistribution[] = [
  { category: 'leakage', label: 'Leakage', percentage: 35, color: '#EF4444' },
  { category: 'no_water', label: 'No Water', percentage: 25, color: '#3B82F6' },
  { category: 'low_pressure', label: 'Low Pressure', percentage: 20, color: '#F59E0B' },
  { category: 'other', label: 'Other', percentage: 20, color: '#94A3B8' },
];

export const MOCK_STAFF: Staff[] = [
  { id: 'staff-001', name: 'Suresh Babu', role: 'Plumber', phone: '+91 87654 32100', available: true },
  { id: 'staff-002', name: 'Anil Sharma', role: 'Technician', phone: '+91 87654 32101', available: true },
  { id: 'staff-003', name: 'Deepak Yadav', role: 'Maintenance Lead', phone: '+91 87654 32102', available: false },
  { id: 'staff-004', name: 'Ravi Prasad', role: 'Plumber', phone: '+91 87654 32103', available: true },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'c-001',
    ticketId: 'TKT-2024-001',
    residentName: 'Ananya Mehta',
    flatNumber: 'A-301',
    issueType: 'leakage',
    priority: 'high',
    status: 'pending',
    description: 'Severe water leakage from the kitchen ceiling. Water is dripping continuously and has damaged the false ceiling tiles. The issue started two days ago and is getting worse.',
    date: '2024-12-15',
    assignedStaff: null,
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-002',
    ticketId: 'TKT-2024-002',
    residentName: 'Vikram Singh',
    flatNumber: 'B-504',
    issueType: 'no_water',
    priority: 'high',
    status: 'in_progress',
    description: 'No water supply since morning. All taps are completely dry. Other residents in the same block seem to have water. Could be a valve issue specific to my flat.',
    date: '2024-12-14',
    assignedStaff: 'staff-001',
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-003',
    ticketId: 'TKT-2024-003',
    residentName: 'Priya Patel',
    flatNumber: 'C-202',
    issueType: 'low_pressure',
    priority: 'medium',
    status: 'pending',
    description: 'Very low water pressure in all bathrooms. The water barely trickles from the shower head. This has been happening for the past week.',
    date: '2024-12-13',
    assignedStaff: null,
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-004',
    ticketId: 'TKT-2024-004',
    residentName: 'Arjun Reddy',
    flatNumber: 'A-102',
    issueType: 'dirty_water',
    priority: 'high',
    status: 'pending',
    description: 'Yellowish/brownish water coming from all taps. The water has a mild metallic smell. Not safe for drinking or cooking. Please investigate urgently.',
    date: '2024-12-13',
    assignedStaff: null,
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-005',
    ticketId: 'TKT-2024-005',
    residentName: 'Sneha Kulkarni',
    flatNumber: 'D-801',
    issueType: 'leakage',
    priority: 'medium',
    status: 'resolved',
    description: 'Minor leakage from the bathroom pipe connection. Small but steady drip near the water heater inlet pipe. Concerned about potential damage to the wall.',
    date: '2024-12-10',
    assignedStaff: 'staff-002',
    resolutionNotes: 'Replaced the faulty pipe connector and applied waterproof sealant. Leak has been completely fixed. Advised resident to monitor for 48 hours.',
    imageUri: null,
  },
  {
    id: 'c-006',
    ticketId: 'TKT-2024-006',
    residentName: 'Rohan Iyer',
    flatNumber: 'B-303',
    issueType: 'no_water',
    priority: 'medium',
    status: 'resolved',
    description: 'Intermittent water supply in the kitchen. Water comes and goes every few minutes. Makes it very difficult to do daily chores.',
    date: '2024-12-09',
    assignedStaff: 'staff-001',
    resolutionNotes: 'Found air lock in the supply line. Bled the pipes and restored consistent water flow. Issue resolved.',
    imageUri: null,
  },
  {
    id: 'c-007',
    ticketId: 'TKT-2024-007',
    residentName: 'Kavitha Nair',
    flatNumber: 'C-605',
    issueType: 'other',
    priority: 'low',
    status: 'in_progress',
    description: 'The water meter seems to be running even when all taps are closed. Suspect there might be a hidden leak somewhere in the plumbing.',
    date: '2024-12-12',
    assignedStaff: 'staff-004',
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-008',
    ticketId: 'TKT-2024-008',
    residentName: 'Amit Deshmukh',
    flatNumber: 'A-405',
    issueType: 'low_pressure',
    priority: 'low',
    status: 'resolved',
    description: 'Low pressure only in the morning hours between 6-8 AM. By afternoon the pressure normalizes. Has been happening for about a month.',
    date: '2024-12-08',
    assignedStaff: 'staff-003',
    resolutionNotes: 'Adjusted the booster pump timing schedule and cleaned the pressure valve filter. Morning pressure restored to normal levels.',
    imageUri: null,
  },
  {
    id: 'c-009',
    ticketId: 'TKT-2024-009',
    residentName: 'Divya Sharma',
    flatNumber: 'D-201',
    issueType: 'leakage',
    priority: 'medium',
    status: 'pending',
    description: 'Water seeping through the balcony wall. Seems to originate from the flat above. The paint is peeling off and the wall is getting damp patches.',
    date: '2024-12-14',
    assignedStaff: null,
    resolutionNotes: null,
    imageUri: null,
  },
  {
    id: 'c-010',
    ticketId: 'TKT-2024-010',
    residentName: 'Manoj Tiwari',
    flatNumber: 'B-107',
    issueType: 'dirty_water',
    priority: 'low',
    status: 'resolved',
    description: 'Occasional white particles visible in the water. Might be calcium deposits. Want to get it checked for quality assurance.',
    date: '2024-12-07',
    assignedStaff: 'staff-002',
    resolutionNotes: 'Installed a new inline sediment filter on the main supply line. Water tested and cleared. Calcium levels within acceptable range.',
    imageUri: null,
  },
];

export const MOCK_NOTICES: WaterNotice[] = [
  {
    id: 'n-001',
    title: 'Water Shutdown - Pipeline Maintenance',
    description: 'Scheduled water shutdown for annual pipeline maintenance and inspection of the main supply line. All blocks (A, B, C, D) will be affected. Residents are advised to store sufficient water beforehand.',
    type: 'shutdown',
    startTime: '2024-12-20 09:00 AM',
    endTime: '2024-12-20 05:00 PM',
    createdBy: 'Rajesh Kumar',
    createdAt: '2024-12-15',
    status: 'scheduled',
  },
  {
    id: 'n-002',
    title: 'Tank Cleaning Schedule',
    description: 'Quarterly overhead tank cleaning and sanitisation for Block A and Block B. Water supply will be temporarily interrupted during cleaning hours. Fresh water will be restored after quality testing.',
    type: 'cleaning',
    startTime: '2024-12-18 06:00 AM',
    endTime: '2024-12-18 12:00 PM',
    createdBy: 'Rajesh Kumar',
    createdAt: '2024-12-14',
    status: 'scheduled',
  },
  {
    id: 'n-003',
    title: 'Pipeline Repair Work',
    description: 'Urgent repair of the underground pipeline connecting Block C to the main water tank. A minor leak was detected during routine inspection. Repair work will be carried out to prevent further damage.',
    type: 'repair',
    startTime: '2024-12-16 10:00 AM',
    endTime: '2024-12-16 04:00 PM',
    createdBy: 'Rajesh Kumar',
    createdAt: '2024-12-13',
    status: 'active',
  },
  {
    id: 'n-004',
    title: 'Water Quality Testing',
    description: 'Monthly water quality testing as per municipal guidelines. Samples will be collected from all blocks and tested for pH, TDS, coliform, and heavy metals. Results will be shared within 3 business days.',
    type: 'testing',
    startTime: '2024-12-17 08:00 AM',
    endTime: '2024-12-17 11:00 AM',
    createdBy: 'Rajesh Kumar',
    createdAt: '2024-12-12',
    status: 'scheduled',
  },
  {
    id: 'n-005',
    title: 'Emergency Water Supply',
    description: 'Due to municipal water supply disruption, tanker water has been arranged for all blocks. Tankers will arrive at 7:00 AM and 5:00 PM. Residents may experience slight variation in water taste and pressure.',
    type: 'emergency',
    startTime: '2024-12-15 07:00 AM',
    endTime: '2024-12-15 09:00 PM',
    createdBy: 'Rajesh Kumar',
    createdAt: '2024-12-15',
    status: 'active',
  },
];
